Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Exclude:
    - 'app/**/*.rb'
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - 'config.ru'
    - 'Capfile'
    - 'Rakefile'
    - '**/*.rake'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
